name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Obtener código
        uses: actions/checkout@v4

      - name: Verificar estructura
        run: ls -la